//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Maintain.rc
//
#define ID_CLOCK_MAINFRAME              10
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAINTATYPE                  129
#define IDB_STATION                     130
#define IDD_INFORMATION_PROMPT          131
#define IDD_LOGIN_DIALOG                132
#define IDB_BITMAP_ZHB                  132
#define IDB_BITMAP_BZZ                  133
#define IDB_BITMAP_CPS                  134
#define IDB_BITMAP_JXX                  135
#define IDD_CONSTRUCT_REQUEST_DIALOG    136
#define IDB_BITMAP_WLZ                  136
#define IDD_CONSTRUCT_QUERY_DIALOG      137
#define IDD_SHOWDISCOMMAND              138
#define IDD_USERMANAGE_DIALOG           139
#define IDB_WARNTYPEL                   140
#define IDD_WARNLOG_DIALOG              141
#define IDB_WARNTYPES                   142
#define IDD_WARNNOTE_DIALOG             143
#define IDI_NEWMESSAGE                  150
#define IDC_LOGIN_NUM                   1000
#define IDC_LOGIN_NAME                  1001
#define IDC_LOGIN_PASSWORD              1003
#define ID_INDICATOR_WAN                1004
#define ID_INDICATOR_TIME               1005
#define ID_INDICATOR_UNIT               1006
#define IDC_CLEAR                       1010
#define ID_USERMANAGE_DEL               1011
#define IDC_BTN_SIGNFOR                 1012
#define IDC_LIST1                       1013
#define IDC_DATETIMEPICKER1             1200
#define IDC_EDIT1                       1201
#define IDC_ORDER                       1203
#define IDC_ORGSEND                     1205
#define IDC_EDIT3                       1206
#define IDC_REGISTER                    1207
#define IDC_COMMANDTITLE                1208
#define IDC_RADIO2                      1209
#define IDC_SAVE                        1210
#define IDC_ASKER                       1211
#define IDC_WATCHER                     1212
#define IDC_CONTENT                     1213
#define IDC_REQUEST                     1215
#define IDC_CRCONTENT                   1216
#define IDC_CCCONTENT                   1217
#define IDC_REGCONTENT                  1218
#define IDC_COMCONTENT                  1219
#define IDC_CCWATCHER                   1229
#define IDC_CCASKER                     1230
#define IDC_OCASKER                     1232
#define IDC_OCWATCHER                   1234
#define IDC_QUERY                       1236
#define IDC_COMBOASKER                  1249
#define IDC_COMBORWATER                 1250
#define IDC_CHECK1                      1251
#define IDC_CHECK2                      1252
#define IDC_CHECK3                      1253
#define IDC_RASKER                      1254
#define IDC_RWATCHER                    1255
#define IDC_CRASKER                     1256
#define IDC_CRWATCHER                   1257
#define IDC_CCORDER                     1258
#define IDC_CCDISPATCHER                1259
#define IDC_COMORDER                    1260
#define IDC_OCDISPATCHER                1261
#define IDC_RDATETIME                   1262
#define IDC_ASKTIME                     1262
#define IDC_CRDATETIME                  1263
#define IDC_CCDATETIME                  1264
#define IDC_OCDATETIME                  1265
#define IDC_CONDATETIME                 1266
#define IDC_EDIT2                       1267
#define IDC_PRINT                       1269
#define IDC_DELETE                      1270
#define IDC_CONSUMETIME                 1273
#define IDC_MENDKIND                    1274
#define IDC_STATION                     1277
#define IDC_STATIONS                    1278
#define IDC_STATIONS2                   1279
#define IDC_SHOWDIS_TITLE               1281
#define IDC_SHOWDIS_CHECKTIME           1282
#define IDC_SHOWDIS_COPYFOR             1283
#define IDC_DISPATCHER                  1284
#define IDC_TIME                        1285
#define IDC_SENDTIME                    1285
#define IDC_SHOWDIS_ORGSEND             1286
#define IDC_SHOWDIS_ORGRECEIVE          1287
#define IDC_SHOWDIS_CHECKER             1288
#define IDC_RADIOREG                    1289
#define IDC_RADIOCCOM                   1290
#define IDC_RADIOOCOM                   1291
#define IDC_RADIOCREG                   1292
#define IDC_REGTITLE                    1293
#define IDC_ORGRECEIVE                  1294
#define IDC_CHECKER                     1295
#define IDC_CHECKTIME                   1296
#define IDC_COPYFOR                     1297
#define IDC_ASKSTATION                  1298
#define IDC_USERMANAGE_NAME             1300
#define IDC_USERMANAGE_USERKIND         1301
#define IDC_USERMANAGE_PASSWORD         1302
#define IDC_USERMANAGE_PASSWORD_CONFIRM 1303
#define ID_USERMANAGE_ADD               1304
#define ID_USERMANAGE_MODIPAS           1305
#define IDC_EDIT_RECIVER                1307
#define IDC_WARNLOGDLG_LIST             2000
#define IDC_WARNLOGDLG_DATE             2001
#define IDC_WARNLOGDLG_STATION          2002
#define IDC_WARNNOTEDLG_CONTENT         2010
#define IDC_WARNNOTEDLG_NUM             2011
#define IDC_WARNNOTEDLG_DATE            2012
#define IDC_WARNNOTEDLG_TIME            2013
#define IDC_WARNNOTEDLG_STATION         2014
#define IDC_WARNNOTEDLG_SOURCE          2015
#define IDC_WARNNOTEDLG_LEVEL           2016
#define IDC_WARNNOTEDLG_PREV            2017
#define IDC_WARNNOTEDLG_NEXT            2018
#define IDC_STATIC_INF                  2020
#define IDC_COMBO_DETAILEDINF           2022
#define IDC_BUTTON_SHOWNEWMSG           2023
#define IDC_EDIT_RECBUR                 2101
#define IDC_EDIT_RECSUBBUR              2102
#define IDC_EDIT_SENDBUR                2103
#define IDC_EDIT_SENDSUBBUR             2104
#define IDC_EDIT_SENDDISPID             2105
#define ID_SYSTEM_LOGIN                 32773
#define ID_SYSTEM_LOGOUT                32774
#define ID_COMMON_SEND                  32775
#define ID_OPERATOR_CONSTRUCTREQUEST    32776
#define ID_OPERATE_CONSTRUCTQUERY       32777
#define ID_TEST                         32778
#define ID_SYSTEM_USERMANAGE            32780
#define IDM_SHOWWARNLOG                 32781
#define ID_VIEW_SHOWWARNLOG             32782
#define ID_VIEW_NEWMESSAGE              32783
#define ID_TOOLS_OPTIONS                32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         2106
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
