//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Resource.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.Resource.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AppDescription 的本地化字符串。
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        internal static string CompanyChsAbbrName {
            get {
                return ResourceManager.GetString("CompanyChsAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        internal static string CompanyChsFullName {
            get {
                return ResourceManager.GetString("CompanyChsFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acl 的本地化字符串。
        /// </summary>
        internal static string CompanyEnAbbrName {
            get {
                return ResourceManager.GetString("CompanyEnAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Name. 的本地化字符串。
        /// </summary>
        internal static string CompanyEnFullName {
            get {
                return ResourceManager.GetString("CompanyEnFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon CompanyIcon {
            get {
                object obj = ResourceManager.GetObject("CompanyIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap companyLogo {
            get {
                object obj = ResourceManager.GetObject("companyLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 © 2017，保留所有权利。 的本地化字符串。
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductEnName 的本地化字符串。
        /// </summary>
        internal static string ProductEnName {
            get {
                return ResourceManager.GetString("ProductEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.0.0 的本地化字符串。
        /// </summary>
        internal static string ProductNumericVersion {
            get {
                return ResourceManager.GetString("ProductNumericVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.0.0 的本地化字符串。
        /// </summary>
        internal static string ProductStringVersion {
            get {
                return ResourceManager.GetString("ProductStringVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectChsName 的本地化字符串。
        /// </summary>
        internal static string ProjectChsName {
            get {
                return ResourceManager.GetString("ProjectChsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectEnName 的本地化字符串。
        /// </summary>
        internal static string ProjectEnName {
            get {
                return ResourceManager.GetString("ProjectEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap splashscreenBkg {
            get {
                object obj = ResourceManager.GetObject("splashscreenBkg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
