//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Maintain.rc
//
#define ID_CLOCK_MAINFRAME              10
#define IDD_ABOUTBOX                    100
#define IDD_OPERATE_DIALOG              101
#define IDR_MAINFRAME                   102
#define IDR_MAINTATYPE                  103
#define IDB_STATION                     104
#define IDD_LOGIN_DIALOG                105
#define IDD_EDITPHRASE_DIALOG           111
#define IDD_CONSTRUCT_REQUEST_DIALOG    112
#define IDD_CONSTRUCT_QUERY_DIALOG      113
#define IDD_SHOWDISCOMMAND              114
#define IDD_WARNLOG_DIALOG              115
#define IDD_SHOWSTATION_DIALOG          120
#define IDB_WARNTYPEL                   121
#define IDB_WARNTYPES                   122
#define IDD_WARNNOTE_DIALOG             123
#define IDD_INFORMATION_PROMPT          130
#define IDD_CLOSEOFF_DIALOG             131
#define IDB_BITMAP_ZHB                  132
#define IDB_BITMAP_BZZ                  133
#define IDB_BITMAP_CPS                  134
#define IDB_BITMAP_JXX                  135
#define IDB_BITMAP_WLZ                  136
#define IDR_MULSTAMENU                  146
#define IDD_PASS_DIALOG                 147
#define IDR_MENU1                       148
#define IDD_DIALOG_LOGPRO               149
#define IDC_LOGIN_NUM                   1000
#define IDC_LOGIN_NAME                  1001
#define IDC_LOGIN_PASSWORD              1002
#define ID_INDICATOR_WAN                1060
#define ID_INDICATOR_TIME               1061
#define ID_INDICATOR_UNIT               1062
#define IDC_OPERATE_NAME                1100
#define IDC_OPERATE_NUMBER              1101
#define IDC_OPERATE_YEAR                1102
#define IDC_OPERATE_MONTH               1103
#define IDC_OPERATE_DAY                 1104
#define IDC_OPERATE_HOUR                1105
#define IDC_OPERATE_MINUTE              1106
#define IDC_OPERATE_DESTINATION         1107
#define IDC_OPERATE_EXTEND              1108
#define IDC_OPERATE_DDYNAME             1109
#define IDC_SENDUNIT                    1110
#define IDC_OPERATE_COPYFOR             1111
#define IDC_OPERATE_RECTIME             1112
#define IDC_OPERATE_READER              1113
#define IDC_OPERATE_CONTENT             1114
#define IDC_OPERATE_SENDENGINE          1115
#define IDC_OPERATE_SENDIMM             1116
#define IDC_OPERATE_CREDENCE            1117
#define IDC_OPERATE_RECALL              1118
#define IDC_OPERATE_ONLINE              1119
#define IDC_OPERATE_LISTADD             1120
#define IDC_OPERATE_LISTMODIFY          1121
#define IDC_OPERATE_LISTDEL             1122
#define IDC_OPERATE_SIGNFOR             1123
#define IDC_OPERATE_NOTARIZED           1124
#define IDC_OPERATE_GROUPADD            1125
#define IDC_OPERATE_GROUPDEL            1126
#define IDC_REGISTER                    1127
#define IDC_OPERATE_INSERTTEXT          1131
#define IDC_OPERATE_ELEMENTADD          1132
#define IDC_OPERATE_ELEMENTMODIFY       1133
#define IDC_OPERATE_ELEMENTDEL          1134
#define IDC_OPERATE_SEND                1135
#define IDC_SEND                        1135
#define IDC_OPERATE_RESEND              1136
#define IDC_OPERATE_TEMPORARY           1137
#define IDC_OPERATE_LIST                1138
#define IDC_OPERATE_GROUP               1139
#define IDC_OPERATE_ELEMENT             1140
#define IDC_OPERATE_TRAINNUM            1141
#define IDC_OPERATE_ENGINE              1142
#define IDC_OPERATE_STATION             1143
#define IDC_EDITPHRASE_EDIT             1144
#define IDC_NEWREGISTER                 1145
#define IDC_CLEAR                       1146
#define IDC_DSEND                       1147
#define IDC_SATION_ADD                  1148
#define IDC_LIST1                       1149
#define IDC_DATETIMEPICKER1             1150
#define IDC_EDIT1                       1151
#define IDC_ORDER                       1152
#define IDC_ORGRECEIVE                  1153
#define IDC_EDIT3                       1154
#define IDC_COPYFOR                     1156
#define IDC_CLOSEREG                    1158
#define IDC_SAVE                        1159
#define IDC_ASKER                       1211
#define IDC_WATCHER                     1212
#define IDC_CONTENT                     1213
#define IDC_REQUEST                     1215
#define IDC_CRCONTENT                   1216
#define IDC_REGONTENT                   1217
#define IDC_COMCONTENT                  1218
#define IDC_OCCONTENT                   1219
#define IDC_CCWATCHER                   1229
#define IDC_CCASKER                     1230
#define IDC_OCASKER                     1232
#define IDC_OCWATCHER                   1234
#define IDC_QUERY                       1236
#define IDC_COMBOASKER                  1249
#define IDC_COMBORWATER                 1250
#define IDC_CHECK1                      1251
#define IDC_CHECK2                      1252
#define IDC_CHECK3                      1253
#define IDC_RASKER                      1254
#define IDC_RWATCHER                    1255
#define IDC_CRASKER                     1256
#define IDC_CRWATCHER                   1257
#define IDC_CCORDER                     1258
#define IDC_COMORDER                    1258
#define IDC_CCDISPATCHER                1259
#define IDC_OCORDER                     1260
#define IDC_OCDISPATCHER                1261
#define IDC_RDATETIME                   1262
#define IDC_ASKTIME                     1263
#define IDC_SENDTIME                    1264
#define IDC_OCDATETIME                  1265
#define IDC_CONDATETIME                 1266
#define IDC_EDIT2                       1267
#define IDC_PRINT                       1269
#define IDC_DELETE                      1270
#define IDC_CONSUMETIME                 1273
#define IDC_MENDKIND                    1274
#define IDC_STATION                     1277
#define IDC_STATIONS                    1278
#define IDC_STATIONS2                   1279
#define IDC_CHECK4                      1280
#define IDC_ASKSTATION                  1281
#define IDC_DISPATCHER                  1284
#define IDC_TIME                        1285
#define IDC_SENDNAME                    1287
#define IDC_RECUNIT                     1288
#define IDC_CHECKER                     1289
#define IDC_CHECKTIME                   1290
#define IDC_RREG                        1293
#define IDC_RCCOMAND                    1294
#define IDC_ROCOMMAND                   1295
#define IDC_RCREG                       1296
#define IDC_REGTITLE                    1297
#define IDC_COMTITLE                    1298
#define IDC_ORGSEND                     1301
#define IDC_STATICCONSUMETIME           1302
#define IDC_STATICMENDKIND              1303
#define IDC_LISTCURSTATION              1304
#define IDC_STATION_DELETE              1305
#define IDC_STATION_ADDALL              1306
#define IDC_STATION_DELALL              1307
#define IDC_LISTALLSTATION              1308
#define IDC_LIST_CONFIRMSTATION         1311
#define IDC_LIST_RESINFO                1312
#define IDC_WARNLOGDLG_LIST             2000
#define IDC_WARNLOGDLG_DATE             2001
#define IDC_WARNLOGDLG_STATION          2002
#define IDC_WARNNOTEDLG_CONTENT         2010
#define IDC_WARNNOTEDLG_NUM             2011
#define IDC_WARNNOTEDLG_DATE            2012
#define IDC_WARNNOTEDLG_TIME            2013
#define IDC_WARNNOTEDLG_STATION         2014
#define IDC_WARNNOTEDLG_SOURCE          2015
#define IDC_WARNNOTEDLG_LEVEL           2016
#define IDC_WARNNOTEDLG_PREV            2017
#define IDC_WARNNOTEDLG_NEXT            2018
#define IDC_STATIC_INF                  2020
#define IDC_COMBO_DETAILEDINF           2022
#define IDC_BUTTON_SHOWNEWMSG           2023
#define IDC_BUTTON_APPLY                2025
#define IDC_LIST_CONTENT                2026
#define IDC_COMBO_DDML_SENDBUREAU       2027
#define IDC_COMBO_DDML_SENDSUBBUREAU    2028
#define IDC_COMBO_DDML_SNEDDISPATCHID   2029
#define IDC_COMBO_DDML_RECEIVEBUREAU    2030
#define IDC_PASSDLG_EDIT                2030
#define IDC_COMBO_DDML_RECSUBBUREAU     2031
#define IDC_PASSDLG_BUTTONDEL           2031
#define IDC_SCROLLBAR1                  2032
#define IDC_PASSDLG_BUTTON0             2032
#define IDC_PASSDLG_BUTTON1             2033
#define IDC_STATIC_INFOR                2033
#define IDC_PASSDLG_BUTTON2             2034
#define IDC_PASSDLG_BUTTON3             2035
#define IDC_PASSDLG_BUTTON4             2036
#define IDC_PASSDLG_BUTTON5             2037
#define IDC_PASSDLG_BUTTON6             2038
#define IDC_PASSDLG_BUTTON7             2039
#define IDC_PASSDLG_BUTTON8             2040
#define IDC_PASSDLG_BUTTON9             2041
#define ID_SYSTEM_LOGIN                 32773
#define ID_SYSTEM_LOGOUT                32774
#define ID_OPERATOR_CONSTRUCTREQUEST    32775
#define ID_OPERATE_CONSTRUCTQUERY       32776
#define ID_OPERATOR_SENDDISPACTHER      32777
#define ID_OPERATOR_SENDOPENDISPACTHER  32778
#define ID_VIEW_SHOWWARNLOG             32779
#define ID_VIEW_SHOWTREEVIEW            32780
#define ID_VIEW_NEWMESSAGE              32781
#define ID_TOOLS_OPTIONS                32782
#define ID_OPERATOR_SINSTASHOW          32786
#define ID_OPERATOR_MULSTASHOW          32787
#define ID_VIEW_SWXHJNAME               32788
#define ID_VIEW_SWWCNAME                32789
#define ID_VIEW_SWDCNAME                32790
#define ID_OPERATOR_MAPMODE_TEXT        32792
#define ID_OPERATOR_MAPMODE_ANSIO       32793
#define ID_OPERATOR_MAPMODE_ISOTRO      32794
#define ID_MENU1_1                      32795
#define ID_MENUITEM32796                32796
#define ID_MENUITEM32797                32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         2034
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
