namespace ProWrite.UI.Controls.Editor
{
	partial class TextInputForm
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            DevExpress.XtraSpellChecker.OptionsSpelling optionsSpelling1 = new DevExpress.XtraSpellChecker.OptionsSpelling();
            //this.spellChecker1 = new DevExpress.XtraSpellChecker.SpellChecker();
            this.memoEdit = new DevExpress.XtraEditors.MemoEdit();
            this.btnCancel = new DevExpress.XtraEditors.SimpleButton();
            this.btnOk = new DevExpress.XtraEditors.SimpleButton();
            this.labelControl1 = new DevExpress.XtraEditors.LabelControl();
            this.barManager1 = new DevExpress.XtraBars.BarManager(this.components);
            this.barDockControlTop = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlBottom = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlLeft = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            this.barButtonItem1 = new DevExpress.XtraBars.BarButtonItem();
            this.popupMenu1 = new DevExpress.XtraBars.PopupMenu(this.components);
            this.sharedDictionaryStorage1 = new DevExpress.XtraSpellChecker.SharedDictionaryStorage(this.components);
            this.listBoxControl1 = new DevExpress.XtraEditors.ListBoxControl();
            ((System.ComponentModel.ISupportInitialize)(this.memoEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.popupMenu1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.listBoxControl1)).BeginInit();
            this.SuspendLayout();
            // 
            // spellChecker1
            // 
            this.spellChecker1.Culture = new System.Globalization.CultureInfo("en");
            this.spellChecker1.ParentContainer = null;
            this.spellChecker1.SpellCheckMode = DevExpress.XtraSpellChecker.SpellCheckMode.AsYouType;
            this.spellChecker1.OptionsFormShowing += new DevExpress.XtraSpellChecker.FormShowingEventHandler(this.spellChecker1_OptionsFormShowing);
            this.spellChecker1.SpellingFormShowing += new DevExpress.XtraSpellChecker.SpellingFormShowingEventHandler(this.spellChecker1_SpellingFormShowing);
            // 
            // memoEdit
            // 
            this.memoEdit.Location = new System.Drawing.Point(7, 28);
            this.memoEdit.Name = "memoEdit";
            this.spellChecker1.SetShowSpellCheckMenu(this.memoEdit, true);
            this.memoEdit.Size = new System.Drawing.Size(227, 104);
            this.spellChecker1.SetSpellCheckerOptions(this.memoEdit, optionsSpelling1);
            this.memoEdit.TabIndex = 0;
            this.memoEdit.MouseDown += new System.Windows.Forms.MouseEventHandler(this.memoEdit_MouseDown);
            this.memoEdit.MouseLeave += new System.EventHandler(this.memoEdit_MouseLeave);
            this.memoEdit.KeyUp += new System.Windows.Forms.KeyEventHandler(this.memoEdit_KeyUp);
            this.memoEdit.KeyDown += new System.Windows.Forms.KeyEventHandler(this.memoEdit_KeyDown);
            this.memoEdit.TextChanged += new System.EventHandler(this.memoEdit_KeyUp);
            // 
            // btnCancel
            // 
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new System.Drawing.Point(188, 138);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(46, 23);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnOk
            // 
            this.btnOk.Location = new System.Drawing.Point(136, 138);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(46, 23);
            this.btnOk.TabIndex = 2;
            this.btnOk.Text = "OK";
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            // 
            // labelControl1
            // 
            this.labelControl1.Location = new System.Drawing.Point(11, 9);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new System.Drawing.Size(68, 13);
            this.labelControl1.TabIndex = 3;
            this.labelControl1.Text = "Input the text";
            // 
            // barManager1
            // 
            this.barManager1.DockControls.Add(this.barDockControlTop);
            this.barManager1.DockControls.Add(this.barDockControlBottom);
            this.barManager1.DockControls.Add(this.barDockControlLeft);
            this.barManager1.DockControls.Add(this.barDockControlRight);
            this.barManager1.Form = this;
            this.barManager1.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.barButtonItem1});
            this.barManager1.MaxItemId = 1;
            this.barManager1.QueryShowPopupMenu += new DevExpress.XtraBars.QueryShowPopupMenuEventHandler(this.barManager1_QueryShowPopupMenu);
            // 
            // barButtonItem1
            // 
            this.barButtonItem1.Caption = "barButtonItem1";
            this.barButtonItem1.Id = 0;
            this.barButtonItem1.Name = "barButtonItem1";
            // 
            // popupMenu1
            // 
            this.popupMenu1.LinksPersistInfo.AddRange(new DevExpress.XtraBars.LinkPersistInfo[] {
            new DevExpress.XtraBars.LinkPersistInfo(this.barButtonItem1)});
            this.popupMenu1.Manager = this.barManager1;
            this.popupMenu1.Name = "popupMenu1";
            // 
            // listBoxControl1
            // 
            this.listBoxControl1.Items.AddRange(new object[] {
            "4 TWENTY",
            "4TWENTY",
            "60 NINE",
            "60NINE",
            "A.S.S.",
            "ANAL",
            "ANAL ANNIE",
            "ANAL SEX",
            "ANALANNIE",
            "ANALSEX",
            "ANUS",
            "ARSE",
            "ASS",
            "ASS BAGGER",
            "ASS BLASTER",
            "ASS CLOWN",
            "ASS COWBOY",
            "ASS FUCK",
            "ASS FUCKER",
            "ASS HOLE",
            "ASS HOLES",
            "ASS HORE",
            "ASS JOCKEY",
            "ASS KISS",
            "ASS KISSER",
            "ASS KLOWN",
            "ASS LICK",
            "ASS LICKER",
            "ASS LOVER",
            "ASS MAN",
            "ASS MONKEY",
            "ASS MUNCH",
            "ASS MUNCHER",
            "ASS PACKER",
            "ASS PIRATE",
            "ASS PUPPIES",
            "ASS RANGER",
            "ASS WHORE",
            "ASS WIPE",
            "ASSBAGGER",
            "ASSBLASTER",
            "ASSCLOWN",
            "ASSCOWBOY",
            "ASSFUCK",
            "ASSFUCKER",
            "ASSHOLE",
            "ASSHOLES",
            "ASSHORE",
            "ASSJOCKEY",
            "ASSKISS",
            "ASSKISSER",
            "ASSKLOWN",
            "ASSLICK",
            "ASSLICKER",
            "ASSLOVER",
            "ASSMAN",
            "ASSMONKEY",
            "ASSMUNCH",
            "ASSMUNCHER",
            "ASSPACKER",
            "ASSPIRATE",
            "ASSPUPPIES",
            "ASSRANGER",
            "ASSWHORE",
            "ASSWIPE",
            "ATHLETES FOOT",
            "ATHLETESFOOT",
            "AXING THE WEASEL",
            "B HARD",
            "BACK DOOR",
            "BACK DOOR MAN",
            "BACKDOOR",
            "BACKDOORMAN",
            "BACKSEAT",
            "BAD ASS",
            "BAD FUCK",
            "BADFUCK",
            "BALL LICKER",
            "BALL SACK",
            "BALLLICKER",
            "BALLS",
            "BALLSACK",
            "BANGING",
            "BARELY LEGAL",
            "BARELYLEGAL",
            "BARF",
            "BARF FACE",
            "BARFACE",
            "BARFFACE",
            "BASTARD",
            "BAZONGAS",
            "BAZOOMS",
            "BEASTALITY",
            "BEASTIALITY",
            "BEAT OFF",
            "BEAT YOUR MEAT",
            "BEATOFF",
            "BEAT-OFF",
            "BEATYOURMEAT",
            "BI",
            "BI SEXUAL",
            "BIATCH",
            "BIG ASS",
            "BIG BITCH",
            "BIG BITCH",
            "BIG BUTT",
            "BIGASS",
            "BIGBASTARD",
            "BIGBUTT",
            "BISEXUAL",
            "BI-SEXUAL",
            "BITCH",
            "BITCHES",
            "BITCHIN",
            "BITCHY",
            "BITE ME",
            "BITEME",
            "BLACK OUT",
            "BLACKOUT",
            "BLOW JOB",
            "BLOWJOB",
            "BM",
            "BONER",
            "BONG",
            "BOOBIES",
            "BOOBS",
            "BOODY",
            "BREAST",
            "BREAST JOB",
            "BREAST LOVER",
            "BREAST MAN",
            "BREASTJOB",
            "BREASTLOVER",
            "BREASTMAN",
            "BUDWEISER",
            "BULL CRAP",
            "BULL DIKE",
            "BULL DYKE",
            "BULL SHIT",
            "BULLCRAP",
            "BULLDIKE",
            "BULLDYKE",
            "BULLSHIT",
            "BUMBLE FUCK",
            "BUMBLEFUCK",
            "BUMFUCK",
            "BUNGHOLE",
            "BUTCH BABES",
            "BUTCH DIKE",
            "BUTCH DYKE",
            "BUTCHBABES",
            "BUTCHDIKE",
            "BUTCHDYKE",
            "BUTT BANG",
            "BUTT FUCK",
            "BUTT FUCKER",
            "BUTT FUCKERS",
            "BUTT HEAD",
            "BUTT MAN",
            "BUTT PLUG",
            "BUTT STAIN",
            "BUTTBANG",
            "BUTT-BANG",
            "BUTTFACE",
            "BUTTFUCK",
            "BUTT-FUCK",
            "BUTTFUCKER",
            "BUTT-FUCKER",
            "BUTTFUCKERS",
            "BUTT-FUCKERS",
            "BUTTHEAD",
            "BUTTMAN",
            "BUTTPIRATE",
            "BUTTPLUG",
            "BUTTSTAIN",
            "CAMEL TOE",
            "CAMELTOE",
            "CARPET MUNCHER",
            "CARPETMUNCHER",
            "CARRUTH",
            "CHERRY POPPER",
            "CHERRYPOPPER",
            "CHICK SLICK",
            "CHICKSLICK",
            "CLAM DIGGER",
            "CLAM DIVER",
            "CLAMDIGGER",
            "CLAMDIVER",
            "CLIT",
            "CLITORIS",
            "COCK",
            "COCK BLOCK",
            "COCK BLOCKER",
            "COCK COWBOY",
            "COCK FIGHT",
            "COCK KNOB",
            "COCK LICKER",
            "COCK LOVER",
            "COCK NOB",
            "COCK QUEEN",
            "COCK RIDER",
            "COCK SMITH",
            "COCK SUCKER",
            "COCK TAIL",
            "COCK TEASE",
            "COCKBLOCK",
            "COCKBLOCKER",
            "COCKCOWBOY",
            "COCKFIGHT",
            "COCKHEAD",
            "COCKKNOB",
            "COCKLICKER",
            "COCKLOVER",
            "COCKNOB",
            "COCKQUEEN",
            "COCKRIDER",
            "COCKS MAN",
            "COCKSMAN",
            "COCKSMITH",
            "COCKSUCER",
            "COCKSUCKER",
            "COCKTAIL",
            "COCKTEASE",
            "COCKY",
            "CONDOM",
            "COPULATE",
            "CORN HOLE",
            "CORNHOLE",
            "CRABS",
            "CRACK",
            "CRACK PIPE",
            "CRACK WHORE",
            "CRACKPIPE",
            "CRACKWHORE",
            "CRACK-WHORE",
            "CRAP",
            "CRAPPY",
            "CREAMY",
            "CROTCH",
            "CROTCH JOCKEY",
            "CROTCH MONKEY",
            "CROTCH ROT",
            "CROTCHJOCKEY",
            "CROTCHMONKEY",
            "CROTCHROT",
            "CUM",
            "CUM BUBBLE",
            "CUM FEST",
            "CUM JOCKEY",
            "CUM QUAT",
            "CUM QUEEN",
            "CUM SHOT",
            "CUMBUBBLE",
            "CUMFEST",
            "CUMJOCKEY",
            "CUMM",
            "CUMMING",
            "CUMQUAT",
            "CUMQUEEN",
            "CUMSHOT",
            "CUNNILINGUS",
            "CUNT",
            "CUNT FUCK",
            "CUNT FUCKER",
            "CUNT LICKER",
            "CUNTFUCK",
            "CUNTFUCKER",
            "CUNTLICKER",
            "CYBER SEX",
            "CYBER SLIMER",
            "CYBERSEX",
            "CYBERSLIMER",
            "DAHMER",
            "DAMN",
            "DAMN IT",
            "DAMNIT",
            "DATNIGGA",
            "DD",
            "DEAP THROAT",
            "DEAPER",
            "DEAPTHROAT",
            "DEEP THROAT",
            "DEEPER",
            "DEEPTHROAT",
            "DEFECATE",
            "DEPOSIT",
            "DEVIL",
            "DICK BRAIN",
            "DICK FART",
            "DICK FOR BRAINS",
            "DICK HEAD",
            "DICK LICK",
            "DICK LICKER",
            "DICK LIKCER",
            "DICK WAD",
            "DICK WEED",
            "DICKBRAIN",
            "DICKFORBRAINS",
            "DICKHEAD",
            "DICKLESS",
            "DICKLICK",
            "DICKLICKER",
            "DICKMAN",
            "DICKWAD",
            "DICKWEED",
            "DIKE",
            "DILDO",
            "DIP STICK",
            "DIPSTICK",
            "DIRTY HO",
            "DIX",
            "DIXIE DIKE",
            "DIXIE DYKE",
            "DIXIEDIKE",
            "DIXIEDYKE",
            "DO ME",
            "DOGGIE STYLE",
            "DOGGIESTYLE",
            "DOGGY STLYE",
            "DOGGYSTYLE",
            "DOME",
            "DONG",
            "DOPE",
            "DOUBLE D",
            "DOUBLED",
            "DRAG QUEEN",
            "DRAGQUEEN",
            "DRAGQWEEN",
            "DRE",
            "DRIP DICK",
            "DRIPDICK",
            "DRUNK",
            "DRUNKEN",
            "DUMB ASS",
            "DUMB BITCH",
            "DUMB FUCK",
            "DUMBASS",
            "DUMBBITCH",
            "DUMBFUCK",
            "EASY SLUT",
            "EASYSLUT",
            "EAT ME",
            "EAT PUSSY",
            "EATBALLS",
            "EATME",
            "EATPUSSY",
            "EJACULATE",
            "ERECTION",
            "EVL",
            "EXCREMENT",
            "F TOYOTA",
            "F.I.N.E.",
            "F.U.C.K.",
            "FACE FUCKER",
            "FACEFUCKER",
            "FAGGOT",
            "FAGOT",
            "FAIRY",
            "FANNY FUCKER",
            "FANNYFUCKER",
            "FART",
            "FAST FUCK",
            "FASTFUCK",
            "FAT ASS",
            "FAT FUCK",
            "FAT FUCKER",
            "FATASS",
            "FATFUCK",
            "FATFUCKER",
            "FATSO",
            "FELLATIO",
            "FEMME",
            "FINGER FOOD",
            "FINGER FUCK",
            "FINGER FUCKER",
            "FINGERFOOD",
            "FINGERFUCK",
            "FINGERFUCKER",
            "FIST FUCK",
            "FIST FUCKER",
            "FISTFUCK",
            "FISTFUCKER",
            "FISTING",
            "FLASHER",
            "FLATULENCE",
            "FLOGGIN THE DOLPHIN",
            "FONDLE",
            "FOOT FUCK",
            "FOOT FUCKER",
            "FOOT LICKER",
            "FOOTACTION",
            "FOOTFUCK",
            "FOOTFUCKER",
            "FOOTLICKER",
            "FOOTSTAR",
            "FORE SKIN",
            "FORESKIN",
            "FORNICATE",
            "FOUR 20",
            "FOUR TWENTY",
            "FOUR20",
            "FOURTWENTY",
            "FREAK FUCK",
            "FREAKFUCK",
            "FREAKY FUCKER",
            "FREAKYFUCKER",
            "FREE 4 ALL",
            "FREE FOR ALL",
            "FREE FUCK",
            "FREE4ALL",
            "FREEFORALL",
            "FREEFUCK",
            "FUCK",
            "FUCK BAG",
            "FUCK BUDDY",
            "FUCK FACE",
            "FUCK FEST",
            "FUCK FREAK",
            "FUCK FRIEND",
            "FUCK HEAD",
            "FUCK HER",
            "FUCK IT",
            "FUCK KNOB",
            "FUCK ME",
            "FUCK ME HARD",
            "FUCK MONKEY",
            "FUCK OFF",
            "FUCK PIG",
            "FUCK THEM",
            "FUCK WHORE",
            "FUCK YOU",
            "FUCKA",
            "FUCKABLE",
            "FUCKBAG",
            "FUCKBUDDY",
            "FUCKED",
            "FUCKED UP",
            "FUCKEDUP",
            "FUCKER",
            "FUCKERS",
            "FUCKFACE",
            "FUCKFEST",
            "FUCKFREAK",
            "FUCKFRIEND",
            "FUCKHEAD",
            "FUCKHER",
            "FUCKIN",
            "FUCKIN A",
            "FUCKIN NUTS",
            "FUCKIN RIGHT",
            "FUCKINA",
            "FUCKING",
            "FUCKING A",
            "FUCKING BITCH",
            "FUCKING NUTS",
            "FUCKINGBITCH",
            "FUCKINNUTS",
            "FUCKINRIGHT",
            "FUCKIT",
            "FUCKKNOB",
            "FUCKME",
            "FUCKMEHARD",
            "FUCKMONKEY",
            "FUCKOFF",
            "FUCKPIG",
            "FUCKWHORE",
            "FUCKYOU",
            "FUDGE PAKCERS",
            "FUN FUCK",
            "FUNFUCK",
            "FUUCK",
            "G UNIT",
            "GANG BANG",
            "GANG BANGER",
            "GANGBANG",
            "GANGBANGER",
            "GAY (editor\'s note: was removed from the list after our original Outsports articl" +
                "e appeared.)",
            "GAY ASS",
            "GAY MUTHA FUCKIN QUEER",
            "GAY PRIDE",
            "GAYMUTHAFUCKINWHORE",
            "GENITAL",
            "GET IT ON",
            "GETITON",
            "GIEHN",
            "GIVE HEAD",
            "GIVEHEAD",
            "GLAZED DONUT",
            "GLAZEDDONUT",
            "GO ME",
            "GO TO HELL",
            "GOD",
            "GOD DAMED MUTHA FUCKA",
            "GOD DAMIT",
            "GOD DAMN",
            "GOD DAMNED",
            "GOD MANIT",
            "GODDAMIT",
            "GODDAMN",
            "GODDAMNED",
            "GODDAMNES",
            "GODDAMNIT",
            "GODDAMNMUTHAFUCKER",
            "GONORREHEA",
            "GONZAGAS",
            "GOOK",
            "GOT JESUS",
            "GOT2HAVEIT",
            "GOTOHELL",
            "G-UNIT",
            "HAND JOB",
            "HANDJOB",
            "HARD ON",
            "HARDER",
            "HARDON",
            "HAREM",
            "HE HATE ME",
            "HEAD FUCK",
            "HEAD LIGHTS",
            "HEADFUCK",
            "HEADLIGHTS",
            "HEHATEME",
            "HELL",
            "HELL NO",
            "HELL YES",
            "HELLNO",
            "HELLYES",
            "HEN HOUSE",
            "HENHOUSE",
            "HERPES",
            "HERSHEY HI WAY",
            "HERSHEYHIGHWAY",
            "HERSHEYHIWAY",
            "HERSHY HIGH WAY",
            "HO",
            "HO MO",
            "HOBO",
            "HOLE",
            "HOLE STUFFER",
            "HOLESTUFFER",
            "HOMO",
            "HOMO BANGERS",
            "HOMO SEXUAL",
            "HOMOBANGERS",
            "HOMOSEXUAL",
            "HONKERS",
            "HONKEY",
            "HOOKER",
            "HOOKERS",
            "HOOTERS",
            "HORE",
            "HORNEY",
            "HORNY",
            "HORSESHIT",
            "HOSE JOB",
            "HOSEJOB",
            "HOSER",
            "HOSTAGE",
            "HOT DAMN",
            "HOT PUSSY",
            "HOT TO TROT",
            "HOT2TROT",
            "HOTDAMN",
            "HOTPUSSY",
            "HOTTOTROT",
            "HUSSY",
            "HUSTLER",
            "I LOVE BEER",
            "I LUV BEER",
            "ID TEN T",
            "ID10T",
            "IDIOT",
            "IDOIT",
            "IN THE ASS",
            "IN THE BUFF",
            "INGIN",
            "INSEST",
            "INTER COURSE",
            "INTER RACIAL",
            "INTERCOURSE",
            "INTERRACIAL",
            "INTHEASS",
            "INTHEBUFF",
            "JACK THE RIPPER",
            "JACKASS",
            "JACKOFF",
            "JACKTHERIPPER",
            "JAP",
            "JAP CRAP",
            "JAPCRAP",
            "JERK OFF",
            "JERKOFF",
            "JESUS CHIRST",
            "JESUSCHRIST",
            "JISM",
            "JIZ",
            "JIZ JUICE",
            "JIZIM",
            "JIZJUICE",
            "JIZZ",
            "JIZZIM",
            "JOINT",
            "JUGGALO",
            "JUGS",
            "K MART",
            "KILL",
            "KILLER",
            "KILLING",
            "KISS ASS",
            "KISSASS",
            "KKK",
            "KMART",
            "KNOCKERS",
            "KOON",
            "KOTEX",
            "KRAP",
            "KRAPPY",
            "KUM",
            "KUM BUBBLE",
            "KUM QUAT",
            "KUMBUBBLE",
            "KUMBULLBE",
            "KUMQUAT",
            "KUNT",
            "KY",
            "KY JELLY",
            "LACTATE",
            "LADY BOOG",
            "LAID",
            "LAP DANCE",
            "LAPDANCE",
            "LESBAIN",
            "LESBAYN",
            "LESBIAN",
            "LESBIN",
            "LESBO",
            "LEZ",
            "LEZ BE",
            "LEZ BE FRIENDS",
            "LEZBE",
            "LEZBEFRIENDS",
            "LEZBO",
            "LEZZ",
            "LEZZO",
            "LICK ME",
            "LICKER",
            "LICKME",
            "LIMP DICK",
            "LIMPDICK",
            "LIMY",
            "LIVE SEX",
            "LIVESEX",
            "LL",
            "LOADED GUN",
            "LOADEDGUN",
            "LOLITA",
            "LOOSER",
            "LOTION",
            "LOVE BONE",
            "LOVE GOO",
            "LOVE GUN",
            "LOVE JUICE",
            "LOVE MUSCLE",
            "LOVE PISTOL",
            "LOVE ROCKET",
            "LOVEBONE",
            "LOVEGOO",
            "LOVEGUN",
            "LOVEJUICE",
            "LOVEMUSCLE",
            "LOVEPISTOL",
            "LOVEROCKET",
            "LOW LIFE",
            "LOWLIFE",
            "LUBE JOB",
            "LUBEJOB",
            "LUCKY CAMEL TOE",
            "LUCKYCAMMELTOE",
            "MAGIC WAND",
            "MAGICWAND",
            "MAMS",
            "MAN HATER",
            "MAN PASTE",
            "MANHATER",
            "MANPASTE",
            "MARY JANE",
            "MARYJANE",
            "MASTABATE",
            "MASTABATER",
            "MASTER BLASTER",
            "MASTERBATE",
            "MASTERBLASTER",
            "MASTRABATOR",
            "MATTRESS PRINCESS",
            "MATTRESSPRINCESS",
            "MEAT BEATTER",
            "MEATBEATTER",
            "MOLEST",
            "MOLESTER",
            "MOLESTOR",
            "MONEY SHOT",
            "MONEYSHOT",
            "MOTHER FUCKER",
            "MOTHER LOVE BONE",
            "MOTHERFUCK",
            "MOTHERFUCKER",
            "MOTHERLOVEBONE",
            "MUFF",
            "MUFF DIVE",
            "MUFF DIVER",
            "MUFF LICKER",
            "MUFFDIVE",
            "MUFFDIVER",
            "MUFFIN DIVER",
            "MUFFINDIVER",
            "MUFFLIKCER",
            "MURDER",
            "MUTHA FUCKER",
            "NAKED",
            "NASTY BITCH",
            "NASTY HO",
            "NASTY SLUT",
            "NASTY WHORE",
            "NASTYBITCH",
            "NASTYHO",
            "NASTYSLUT",
            "NASTYWHORE",
            "NEON DEON",
            "NIG",
            "NIGER",
            "NIGGA",
            "NIGGER",
            "NIPPLE",
            "NIPPLE RING",
            "NIPPLERING",
            "NIT TIT",
            "NITTIT",
            "NO FUCKING WAY",
            "NO SEX",
            "NOFUCKINGWAY",
            "NOOKIE",
            "NOONER",
            "NUDE",
            "NUT FUCKER",
            "NUTFUCKER",
            "OICU812",
            "ON THE RAG",
            "ONTHERAG",
            "ORGASM",
            "ORGY",
            "OU812",
            "OUI",
            "P I M P",
            "PEARL NECKLACE",
            "PEARLNECKLACE",
            "PECKER",
            "PEE",
            "PEEP SHOW",
            "PEEPSHOW",
            "PEEPSHPW",
            "PENETRATION",
            "PENIS",
            "PENTHOUSE",
            "PERIOD",
            "PHQUE",
            "PIMP",
            "PIMP SIMP",
            "PIMPED",
            "PIMPER",
            "PIMPJUIC",
            "PIMPJUICE",
            "PIMPSIMP",
            "PISS",
            "PISS HEAD",
            "PISSED",
            "PISSER",
            "PISSHEAD",
            "PLAY BOY",
            "PLAY GIRL",
            "PLAYBOY",
            "PLAYGIRL",
            "POCKET POOL",
            "POCKETPOOL",
            "POLACK",
            "POON TANG",
            "POONTANG",
            "POOP",
            "POOPER",
            "POOR WHITE TRASH",
            "POORWHITETRASH",
            "POPIMP",
            "PORCH MONKEY",
            "PORCHMONKEY",
            "PORN",
            "PORN FLICK",
            "PORN KING",
            "PORN PRINCESS",
            "PORNFLICK",
            "PORNKING",
            "PORNO",
            "PORNPRINCESS",
            "POT",
            "PREMATURE",
            "PRICK",
            "PRICK HEAD",
            "PRICKHEAD",
            "PRIMETIME",
            "PROSTITUTE",
            "PUBIC",
            "PUBIC LICE",
            "PUBICLICE",
            "PUD",
            "PUD BOY",
            "PUDBOY",
            "PUDD",
            "PUDD BOY",
            "PUDDBOY",
            "PUN TANG",
            "PUNTANG",
            "PURINA PRINCESS",
            "PURINAPRICNESS",
            "PUSSY",
            "PUSSY CAT",
            "PUSSY EATER",
            "PUSSY FUCKER",
            "PUSSY LICKER",
            "PUSSY LIPS",
            "PUSSY LOVER",
            "PUSSY POUNDER",
            "PUSSYCAT",
            "PUSSYEATER",
            "PUSSYFUCKER",
            "PUSSYLICKER",
            "PUSSYLIPS",
            "PUSSYLOVER",
            "PUSSYPOUNDER",
            "PUTT PIRATE",
            "PWT",
            "QUEEF",
            "QUEER",
            "QUICKIE",
            "RAE CARRUTH",
            "RAPE",
            "RAPIST",
            "REAR END",
            "REAR ENTRY",
            "REAREND",
            "REARENTRY",
            "RECTUM",
            "RED LIGHT",
            "REDLIGHT",
            "REEFER",
            "RENT A FUCK",
            "RENTAFUCK",
            "RETARD",
            "RETARDED",
            "RIBBED",
            "RIM JOB",
            "RIMJOB",
            "ROACH",
            "ROBBER",
            "S AND M",
            "S&M",
            "SAMCKDADDY",
            "SANDM",
            "SATAN",
            "SCHLONG",
            "SCREW",
            "SCREW YOU",
            "SCREWYOU",
            "SCROTUM",
            "SEMEN",
            "SEX",
            "SEX FARM",
            "SEX HOUND",
            "SEX HOUSE",
            "SEX KITTEN",
            "SEX POT",
            "SEX SLAVE",
            "SEX TO GO",
            "SEX TOY",
            "SEX TOYS",
            "SEX WHORE",
            "SEXFARM",
            "SEXHOUND",
            "SEXHOUSE",
            "SEXKITTEN",
            "SEXPOT",
            "SEXSLAVE",
            "SEXTOGO",
            "SEXTOY",
            "SEXTOYS",
            "SEXUAL",
            "SEXWHORE",
            "SEXY",
            "SEXY BIATCH",
            "SEXY BITCH",
            "SEXY MOMA",
            "SEXY SLIM",
            "SEXYMOMA",
            "SEXY-SLIM",
            "SHAG",
            "SHAGGIN",
            "SHAGGING",
            "SHAWTYPIMP",
            "SHIT",
            "SHIT DICK",
            "SHIT EATER",
            "SHIT FACE",
            "SHIT FOR BRAINS",
            "SHIT FUCK",
            "SHIT FUCKER",
            "SHIT HAPPENS",
            "SHIT HEAD",
            "SHIT OUT OF LUCK",
            "SHIT STAIN",
            "SHIT4BRAINS",
            "SHITDICK",
            "SHITEATER",
            "SHITFACE",
            "SHITFORBRAINS",
            "SHITFUCK",
            "SHITFUCKER",
            "SHITHAPENS",
            "SHITHAPPENS",
            "SHITHEAD",
            "SHITOUTOFLUCK",
            "SHITS",
            "SHITSTAIN",
            "SHITTER",
            "SHITTING",
            "SHITTY",
            "SHORT FUCK",
            "SHORTFUCK",
            "SHOWTIME",
            "SIX SIX SIX",
            "SIXSIXSIX",
            "SIXTY 9",
            "SIXTY NINE",
            "SIXTY9",
            "SIXTYNINE",
            "SKANK",
            "SKANK BITCH",
            "SKANK FUCK",
            "SKANK WHORE",
            "SKANKBITCH",
            "SKANKFUCK",
            "SKANKWHORE",
            "SKANKY BITCH",
            "SKANKY WHORE",
            "SKANKYBITCH",
            "SKANKYWHORE",
            "SKIN FLUTE",
            "SKINFLUTE",
            "SKUM",
            "SKUM BAG",
            "SKUMBAG",
            "SLANT",
            "SLANT EYE",
            "SLANTEYE",
            "SLAVE",
            "SLAVE DRIVER",
            "SLAVEDRIVER",
            "SLEEZE BAG",
            "SLEEZE BALL",
            "SLEEZEBAG",
            "SLEEZEBALL",
            "SLIDE IT IN",
            "SLIDEITIN",
            "SLIME",
            "SLIME BALL",
            "SLIME BUCKET",
            "SLIMEBALL",
            "SLIMEBUCKET",
            "SLUT",
            "SLUT WEAR",
            "SLUT WHORE",
            "SLUTS",
            "SLUTT",
            "SLUTTING",
            "SLUTTY",
            "SLUTWEAR",
            "SLUTWHORE",
            "SMACK DADDY",
            "SMACK THE MONKEY",
            "SMACKTHEMONKEY",
            "SMAGMA",
            "SMART ASS",
            "SNATCH",
            "SNATCH PATCH",
            "SNATCHPATCH",
            "SNIPER",
            "SNOT",
            "SOB",
            "SODOMITE",
            "SODOMY",
            "SON OF A BITCH",
            "SONOFABITCH",
            "SONOFBITCH",
            "SPANK THE MONKEY",
            "SPANKTHEMONKEY",
            "SPERM",
            "SPERM BAG",
            "SPERM HEARDER",
            "SPERM HERDER",
            "SPERMACIDE",
            "SPERMBAG",
            "SPERMHEARDER",
            "SPERMHERDER",
            "SPIC",
            "SPICK",
            "SPIT",
            "SPITTER",
            "SPLIT TAIL",
            "SPLIT TIAL",
            "SPLITTAIL",
            "STAGG",
            "STRAP ON",
            "STRAPON",
            "STRINGER",
            "STRIP CLUB",
            "STRIPCLUB",
            "STROKE",
            "STROKING",
            "STUPID",
            "STUPID FUCK",
            "STUPID FUCKER",
            "STUPIDFUCK",
            "STUPIDFUCKER",
            "SUCK",
            "SUCK DICK",
            "SUCK ME",
            "SUCK MY ASS",
            "SUCK MY DICK",
            "SUCK MY TIT",
            "SUCK OFF",
            "SUCKDICK",
            "SUCKER",
            "SUCKME",
            "SUCKMYASS",
            "SUCKMYDICK",
            "SUCKMYTIT",
            "SUCKOFF",
            "SUICIDE",
            "SWALLOW",
            "SWALLOWER",
            "SWALOW",
            "SWEETNESS",
            "SWIGN DIXX",
            "SWING DIXX",
            "SWINGIN DIXX",
            "SWINGING DICKS",
            "SYPHILIS",
            "TAMPON",
            "TANG",
            "TESTICLE",
            "TESTICLES",
            "THIRD EYE",
            "THIRD LEG",
            "THIRDEYE",
            "THIRDLEG",
            "THREE SOME",
            "THREESOME",
            "TIT",
            "TIT BIT NIPPLY",
            "TIT FUCK",
            "TIT FUCKER",
            "TIT FUCKIN",
            "TIT JOB",
            "TIT LICKER",
            "TIT LOVER",
            "TITBITNIPPLY",
            "TITFUCK",
            "TITFUCKER",
            "TITFUCKIN",
            "TITJOB",
            "TITLICKER",
            "TITLOVER",
            "TITS",
            "TITTIES",
            "TITTY",
            "TOILET",
            "TOILET BOWL",
            "TONGETHRUSTER",
            "TONGUE",
            "TONGUE THRUSTER",
            "TONGUE TRAMP",
            "TONGUETHRUST",
            "TONGUETRAMP",
            "TOUNG THRUSTER",
            "TOUNGE BALLER",
            "TOUNGE THRUST",
            "TRAILER TRASH",
            "TRAILERTRASH",
            "TRAMP",
            "TRI SEXUAL",
            "TRIPLE X",
            "TRIPLEX",
            "TRISEXUAL",
            "TROJAN",
            "TROTS",
            "TUNNEL OF LOVE",
            "TUNNELOFLOVE",
            "TURD",
            "TWO BIT WHORE",
            "TWO ON ONE",
            "TWOBITWHORE",
            "UNFUCKABLE",
            "UP THE ASS",
            "UP THE BUTT",
            "UPSKIRT",
            "UPTHEASS",
            "UPTHEBUTT",
            "URINATE",
            "URINE",
            "UTERUS",
            "VAGINA",
            "VAGINAL",
            "VD",
            "VIBRATER",
            "VIBRATOR",
            "VIRGIN",
            "VIRGIN BREAKER",
            "VIRGINBREAKER",
            "VULVA",
            "WAYSTED",
            "WEENIE",
            "WET SPOT",
            "WETSPOT",
            "WHACKER",
            "WHISKEY DICK",
            "WHISKEYDICK",
            "WHISKY DICK",
            "WHISKYDICK",
            "WHITE TRASH",
            "WHITETRASH",
            "WHORE",
            "WHORE FUCKER",
            "WHORE HOUSE",
            "WHOREFUCKER",
            "WHOREHOUSE",
            "WIGGER",
            "WILLIE WANKER",
            "WILLIEWANKER",
            "WUUTANG",
            "XXX",
            "YELLOW MAN",
            "YELLOWMAN"});
            this.listBoxControl1.Location = new System.Drawing.Point(10, 138);
            this.listBoxControl1.Name = "listBoxControl1";
            this.listBoxControl1.Size = new System.Drawing.Size(120, 95);
            this.listBoxControl1.TabIndex = 4;
            this.listBoxControl1.Visible = false;
            // 
            // TextInputForm
            // 
            this.AcceptButton = this.btnOk;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.btnCancel;
            this.ClientSize = new System.Drawing.Size(240, 167);
            this.Controls.Add(this.listBoxControl1);
            this.Controls.Add(this.labelControl1);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.memoEdit);
            this.Controls.Add(this.barDockControlLeft);
            this.Controls.Add(this.barDockControlRight);
            this.Controls.Add(this.barDockControlBottom);
            this.Controls.Add(this.barDockControlTop);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "TextInputForm";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Input the text";
            this.Load += new System.EventHandler(this.TextInputForm_Load);
            //this.
            ((System.ComponentModel.ISupportInitialize)(this.memoEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.popupMenu1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.listBoxControl1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

        //private MyTextBox memoEdit;
        //private SpellAndDirtyWordChecker spellChecker1;
        private DevExpress.XtraEditors.MemoEdit memoEdit;
        private DevExpress.XtraSpellChecker.SpellChecker spellChecker1;

		private DevExpress.XtraEditors.SimpleButton btnCancel;
		private DevExpress.XtraEditors.SimpleButton btnOk;
        private DevExpress.XtraEditors.LabelControl labelControl1;
        
       
        private DevExpress.XtraBars.BarManager barManager1;
        private DevExpress.XtraBars.BarDockControl barDockControlTop;
        private DevExpress.XtraBars.BarDockControl barDockControlBottom;
        private DevExpress.XtraBars.BarDockControl barDockControlLeft;
        private DevExpress.XtraBars.BarDockControl barDockControlRight;
        private DevExpress.XtraBars.BarButtonItem barButtonItem1;
        private DevExpress.XtraBars.PopupMenu popupMenu1;
        protected DevExpress.XtraSpellChecker.SharedDictionaryStorage sharedDictionaryStorage1;
        private DevExpress.XtraEditors.ListBoxControl listBoxControl1;
	}
}