// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using NUnit.Framework;
using System;
using System.Text;
using System.Collections.Generic;
using ProWrite.Core;
namespace ProWrite.Commons.Test
{
    [TestFixture()]
    public class MessageBusTest
    {


        [Test()]
        public void SendTest()
        {
            //MessageBus.Subject<PWMessage<int>>().Observers += delegate(object sender, PWMessage<int> msg)
            //{
            //    Console.WriteLine(msg.Content);
            //    Assert.AreEqual<int>(100, msg.Content);
            //}
            //;
            //PWMessage e = new PWMessage<int>(100); // TODO: Initialize to an appropriate value
            //ProWrite.Core.MessageBus.Send(null, e);

        }

        [Test()]
        public void SubjectTest()
        {
            // System.Subject<TMessage> expected = null;
            // System.Subject<TMessage> actual;
            // 
            // actual = ProWrite.Core.MessageBus.Subject();
            // 
            // Assert.AreEqual(expected, actual, "ProWrite.Core.MessageBus.Subject<TMessage> did not return the expected value.");
        }

    }


}
