// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using NUnit.Framework;
using System;
using System.Text;
using System.Collections.Generic;
namespace ProWrite.Commons.Test
{
	/// <summary>
	///This is a test class for ProWrite.Resources.Resource and is intended
	///to contain all ProWrite.Resources.Resource Unit Tests
	///</summary>
	[TestFixture()]
	public class ResourceTest
	{


		/// <summary>
		///A test for GetString (string)
		///</summary>
		[Test()]
		public void GetStringTest()
		{
			string name = "ProductName"; 

			string expected = "ProWrite";
			string actual;

			actual = ProWrite.Resources.Resource.GetString(name);

			Assert.AreEqual(expected, actual, "ProWrite.Resources.Resource.GetString did not return the expected value.");

		}

	}


}
