//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProWrite.UFE.Properties
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
        
		private static global::System.Resources.ResourceManager resourceMan;
        
		private static global::System.Globalization.CultureInfo resourceCulture;
        
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
        
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tamir.SharpSsh.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
        
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to 3des-cbc,aes128-cbc.
		/// </summary>
		internal static string kexinit_cipher_c2s {
			get {
				return ResourceManager.GetString("kexinit_cipher_c2s", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to 3des-cbc,aes128-cbc.
		/// </summary>
		internal static string kexinit_cipher_s2c {
			get {
				return ResourceManager.GetString("kexinit_cipher_s2c", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to none.
		/// </summary>
		internal static string kexinit_compression_c2s {
			get {
				return ResourceManager.GetString("kexinit_compression_c2s", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to none.
		/// </summary>
		internal static string kexinit_compression_s2c {
			get {
				return ResourceManager.GetString("kexinit_compression_s2c", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1.
		/// </summary>
		internal static string kexinit_kex {
			get {
				return ResourceManager.GetString("kexinit_kex", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string kexinit_lang_c2s {
			get {
				return ResourceManager.GetString("kexinit_lang_c2s", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string kexinit_lang_s2c {
			get {
				return ResourceManager.GetString("kexinit_lang_s2c", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to hmac-md5,hmac-sha1.
		/// </summary>
		internal static string kexinit_mac_c2s {
			get {
				return ResourceManager.GetString("kexinit_mac_c2s", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to hmac-md5,hmac-sha1.
		/// </summary>
		internal static string kexinit_mac_s2c {
			get {
				return ResourceManager.GetString("kexinit_mac_s2c", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to ssh-rsa,ssh-dss.
		/// </summary>
		internal static string kexinit_server_host_key {
			get {
				return ResourceManager.GetString("kexinit_server_host_key", resourceCulture);
			}
		}
	}
}